### ISSUE TITLE
Uploading to PyPI

### ISSUE THREAD

**Issue by ianporada** [boberle/corefconversion#9]
I find the functions in conll_transform quite useful and suggest packaging and uploading to PyPI if it's not too much trouble.

**Comment by boberle** [comment]
Yes, this is a good idea :smile:. I will try to do that this week!

**Comment by ianporada** [comment]
Awesome! I made an example at https://test.pypi.org/project/conll-coref-transform/ containing the conll_transform file to use in the meantime:

```
pip install -i https://test.pypi.org/simple/ conll-coref-transform
```

```python
from conll_coref_transform import conll_transform
```

**Comment by boberle** [comment]
Sorry for the delay. I have uploaded it to PyPI. It is accessible [here](https://pypi.org/project/conll-transform/), with the list of functions that are available in the package. You can install it with:

```bash
pip3 install conll-transform
```

To use it, just import the functions from `conll_transform`, for example:

```python
from conll_transform import read_files

documents = read_files("myfile.conll", "myfile2.conll")
print(documents)
```
